server:
  port: 8080 # \u7AEF\u53E3
  servlet:
    context-path: /onlineCourse

spring:
  application:
    name: service-settings # \u5E94\u7528\u540D\u79F0
  datasource:
    url: jdbc:mysql://localhost:3306/online_course?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # springboot 2.0后默认禁止重复定义bean，这里取消禁止
  main:
    allow-bean-definition-overriding: true

# \u914D\u7F6E Eureka Server \u6CE8\u518C\u4E2D\u5FC3
eureka:
  client:
    register-with-eureka: false         # \u662F\u5426\u5C06\u81EA\u5DF1\u6CE8\u518C\u5230\u6CE8\u518C\u4E2D\u5FC3\uFF0C\u9ED8\u8BA4\u4E3A true
    registry-fetch-interval-seconds: 5 # \u8868\u793A Eureka Client \u95F4\u9694\u591A\u4E45\u53BB\u670D\u52A1\u5668\u62C9\u53D6\u6CE8\u518C\u4FE1\u606F\uFF0C\u9ED8\u8BA4\u4E3A 30 \u79D2
    service-url:                        # \u8BBE\u7F6E\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
      defaultZone: http://localhost:8761/eureka/
