server:
  port: 8761 # \u7AEF\u53E3

spring:
  application:
    name: eureka-server # \u5E94\u7528\u540D\u79F0

# \u914D\u7F6E Eureka Server \u6CE8\u518C\u4E2D\u5FC3
eureka:
  instance:
    hostname: localhost			  # \u4E3B\u673A\u540D\uFF0C\u4E0D\u914D\u7F6E\u7684\u65F6\u5019\u5C06\u6839\u636E\u64CD\u4F5C\u7CFB\u7EDF\u7684\u4E3B\u673A\u540D\u6765\u83B7\u53D6
    prefer-ip-address: true       # \u542F\u7528ip\u547D\u540D
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    register-with-eureka: false   # \u662F\u5426\u5C06\u81EA\u5DF1\u6CE8\u518C\u5230\u6CE8\u518C\u4E2D\u5FC3\uFF0C\u9ED8\u8BA4\u4E3A true
    fetch-registry: false         # \u662F\u5426\u4ECE\u6CE8\u518C\u4E2D\u5FC3\u83B7\u53D6\u670D\u52A1\u6CE8\u518C\u4FE1\u606F\uFF0C\u9ED8\u8BA4\u4E3A true
    service-url:                  # \u6CE8\u518C\u4E2D\u5FC3\u5BF9\u5916\u66B4\u9732\u7684\u6CE8\u518C\u5730\u5740
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

